
XLIM<-c(13.0,85.0)
#data0 <- read.table("Sn_tetra_reflection.txt",skip=1)#data0[8]が2theta
data1 <- read.table("Sn_cubic_data.int",skip=2)
data2 <- read.table("Sn_tetra_data.int",skip=2)
data3 <- read.table("Ge_data.int",skip=2)
data4 <- read.table("Ge_20190122_mid.txt",skip=18)
data5 <- read.table("SnonGe-Kenma#2000-K2SnO3aq_20190122_mid.txt",skip=18)
data6 <- read.table("SnonGe-No-Kenma-K2SnO3aq_20190122_mid.txt",skip=18)


png("intensity_etched_Sn_on_Ge.png", width = 1000, height = 1900)  # 描画デバイスを開く
split.screen(figs = c(7, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,100)
plot(data.frame(data1[1],data1[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: alpha-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,100)
plot(data.frame(data2[1],data2[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,100)
plot(data.frame(data3[1],data3[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="purple",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("purple"), legend=c("Reference: Ge"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,350)
plot(data.frame(data4[1],data4[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Ge"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,350)
plot(data.frame(data5[1],data5[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Sn on the polished Ge"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(6)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,350)
plot(data.frame(data6[1],data6[2]),xlim=XLIM,ylim=YLIM,xlab="2theta",ylab="cps",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Sn on Ge"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
dev.off()  



XLIM<-c(13.0,85.0)
#data0 <- read.table("Sn_tetra_reflection.txt",skip=1)#data0[8]が2theta
data1 <- read.table("Sn_cubic_data.int",skip=2)
data2 <- read.table("Sn_tetra_data.int",skip=2)
data3 <- read.table("Si-wefer-2_20190122_mid.txt",skip=18)
data4 <- read.table("SnonSi_Kenma#2000_K2SnO3aq_20190122_mid.txt",skip=18)
data5 <- read.table("SnonSi_No-Kenma_K2SnO3aq_20190122_mid.txt",skip=18)

png("intensity_etched_Sn_on_Si.png", width = 1000, height = 1700)  # 描画デバイスを開く
split.screen(figs = c(6, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data1[1],data1[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: alpha-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data2[1],data2[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data3[1],data3[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Si_wafer"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data4[1],data4[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Sn on the polished Si"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data5[1],data5[2]),xlim=XLIM,ylim=YLIM,xlab="2theta",ylab="cps",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Sn on Si"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
dev.off()  

XLIM<-c(20.0,25.0)
png("intensity_etched_Sn_on_Si2.png", width = 1000, height = 1700)  # 描画デバイスを開く
split.screen(figs = c(6, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data1[1],data1[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: alpha-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data2[1],data2[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data3[1],data3[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Si_wafer"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data4[1],data4[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Sn on the polished Si"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,500)
plot(data.frame(data5[1],data5[2]),xlim=XLIM,ylim=YLIM,xlab="2theta",ylab="cps",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Sn on Si"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
dev.off()  
