
XLIM<-c(13.0,85.0)
data0 <- read.table("Sn_tetra_reflection.txt",skip=1)#data0[8]が2theta
data1 <- read.table("Sn_tetra_data.int",skip=2)
data2 <- read.table("181122_sample1.txt",skip=18)
data3 <- read.table("181122_sample2.txt",skip=18)
data4 <- read.table("181122_sample3.txt",skip=18)
data5 <- read.table("181122_sample6.txt",skip=18)

png("intensity_asgrown_samples.png", width = 1000, height = 1500)  # 描画デバイスを開く
split.screen(figs = c(6, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0.002,100)
plot(data.frame(data1[1],data1[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(40,5500)
plot(data.frame(data2[1],data2[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Ge1% quenched (sample1)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(40,5500)
plot(data.frame(data3[1],data3[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Ge0.5% quenched (sample2)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(125,10000)
plot(data.frame(data4[1],data4[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Ge0.1% quenched (sample3)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(61,2600)
plot(data.frame(data5[1],data5[2]),xlim=XLIM,ylim=YLIM,xlab="2theta",ylab="counts",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Ge1% slow-cooled (sample6)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
dev.off()  

png("intensity_asgrown_samples_log.png", width = 1000, height = 1500)  # 描画デバイスを開く
split.screen(figs = c(6, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0.002,150)
plot(data.frame(data1[1],data1[2]),log="y",xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(40,4000)
plot(data.frame(data2[1],data2[2]),log="y",xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Ge1% quenched (sample1)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(40,4000)
plot(data.frame(data3[1],data3[2]),log="y",xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Ge0.5% quenched (sample2)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(125,12500)
plot(data.frame(data4[1],data4[2]),log="y",xlim=XLIM,ylim=YLIM,xlab="",ylab="counts",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Ge0.1% quenched (sample3)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(61,6100)
plot(data.frame(data5[1],data5[2]),log="y",xlim=XLIM,ylim=YLIM,xlab="2aa",ylab="counts",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Ge1% slow-cooled (sample6)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
dev.off()  