png("intensity_asgrown_samples.png", width = 600, height = 1000)  # 描画デバイスを開く

XLIM<-c(10.0,90.0)
YLIM<-c(0,1000)
data1 <- read.table("Sn_tetra_data.int",skip=2)
data2 <- read.table("181122_sample1.txt",skip=18)
data3 <- read.table("181122_sample2.txt",skip=18)
data4 <- read.table("181122_sample3.txt",skip=18)
data5 <- read.table("181122_sample6.txt",skip=18)
split.screen(figs = c(5, 1))
screen(1)
par(mar = c(2, 5, 1, 1),oma = c(1, 1, 1, 1))
plot(data.frame(data1[1],data1[2]),xlim=XLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=0.1)
legend("topright", col=c("red"), legend=c("Reference: beta-Sn"),pch=c(1,1))
par(new=TRUE) 
screen(2)
par(mar = c(2, 5, 1, 1),oma = c(1, 1, 1, 1))
plot(data.frame(data2[1],data2[2]),xlim=XLIM,xlab="",ylab="counts",type="l",col="blue",cex=0.1)
legend("topright", col=c("blue"), legend=c("Ge1% quenched (sample1)"),pch=c(1,1))
par(new=TRUE)
screen(3)
par(mar = c(2, 5, 1, 1),oma = c(1, 1, 1, 1))
plot(data.frame(data3[1],data3[2]),xlim=XLIM,xlab="",ylab="counts",type="l",col="green",cex=0.1)
legend("topright", col=c("green"), legend=c("Ge0.5% quenched (sample2)"),pch=c(1,1))
par(new=TRUE)
screen(4)
par(mar = c(2, 5, 1, 1),oma = c(1, 1, 1, 1))
plot(data.frame(data4[1],data4[2]),xlim=XLIM,xlab="",ylab="counts",type="l",col="gray",cex=0.1)
legend("topright", col=c("gray"), legend=c("Ge0.1% quenched (sample3)"),pch=c(1,1))
par(new=TRUE)
screen(5)
par(mar = c(2, 5, 1, 1),oma = c(1, 1, 1, 1))
plot(data.frame(data5[1],data5[2]),xlim=XLIM,xlab="",ylab="counts",type="l",col="black",cex=0.1)
legend("topright", col=c("black"), legend=c("Ge1% slow-cooled (sample6)"),pch=c(1,1))

dev.off()  

#cd Documents/GitManagedProjects-Kagawalab/研究/抵抗測定/