
XLIM<-c(20.0,80.0)
data_alphaSn <- read.table("../Sn_cubic/Sn_cubic_data.int",skip=2)
data_betaSn <- read.table("../Sn_tetra/Sn_tetra_data.int",skip=2)
data_Si <- read.table("../Si/Si_data.int",skip=2)
data1 <- read.csv("20190517_2tt_20-80.csv",skip=618)
data2 <- read.table("../190306/SnonSi_Kenma#2000_K2SnO3aq_20190122_mid.txt",skip=18)

png("intensity_plated_Sn_on_Si.png", width = 1000, height = 1000)  # 描画デバイスを開く
split.screen(figs = c(6, 1))
screen(1)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data_alphaSn[1],data_alphaSn[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="red",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("red"), legend=c("Reference: alpha-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE) 
screen(2)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data_betaSn[1],data_betaSn[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="blue",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("blue"), legend=c("Reference: beta-Sn"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(3)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,110)
plot(data.frame(data_Si[1],data_Si[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="Intensity(%)",type="l",col="green",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("green"), legend=c("Reference: Si"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(4)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,1000)
plot(data.frame(data1[1],data1[2]),xlim=XLIM,ylim=YLIM,xlab="",ylab="cps",type="l",col="black",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("black"), legend=c("Plated Sn on Si(001): #1 after heat  (190517)"),pch=c(1),cex=2,pt.cex = 2)
par(new=TRUE)
screen(5)
par(mar = c(0, 6, 0, 1),oma = c(1, 1, 1, 1))
YLIM<-c(0,700)
plot(data.frame(data2[1],data2[2]),xlim=XLIM,ylim=YLIM,xlab="2theta",ylab="cps",type="l",col="gray",cex=1,tcl=1,cex.lab=2,cex.axis=2,cex.main=2)
legend("topright", col=c("gray"), legend=c("Plated Sn on Si(001): #2 before heat (190306)"),pch=c(1),cex=2,pt.cex = 2)
dev.off()  
